version: "3"
services:
  syo_db:
    image: postgres:16-alpine
    container_name: syo_db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=payments_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:cached
